import { ProjectData } from "@/interfaces/project";
import { createSlice } from "@reduxjs/toolkit";

const initialProject: any = {
    Column: {
        id: 0,
        bar_spacing: 0,
        border_radius: 0,
        border_bld: 0,
        border_color: "",
        isLegend: false,
        legend_size: 0,
        is_legend_italic: false,
        is_legend_bold: false,
        legend_color: "",
        isAxis: false,
        axis_txt_size: 0,
        is_axis_txt_italic: false,
        is_axis_txt_bold: false,
        axis_txt_color: "",
        axisX: "",
        axisY: "",
        projectId: 0,
    },
    Bars: {
        id: 0,
        bar_spacing: 0,
        border_radius: 0,
        border_bld: 0,
        border_color: "",
        isLegend: false,
        legend_size: 0,
        is_legend_italic: false,
        is_legend_bold: false,
        legend_color: "",
        isAxis: false,
        axis_txt_size: 0,
        is_axis_txt_italic: false,
        is_axis_txt_bold: false,
        axis_txt_color: "",
        axisX: "",
        axisY: "",
        projectId: 0,
    },
    Pie: {
        id: 0,
        start_angle: 0,
        isLegend: false,
        legend_size: 0,
        is_legend_italic: false,
        is_legend_bold: false,
        legend_color: "",
        projectId: 0,
    },
    Donut: {
        id: 0,
        start_angle: 0,
        inner_radius: 0,
        isLegend: false,
        legend_size: 0,
        is_legend_italic: false,
        is_legend_bold: false,
        legend_color: "",
        projectId: 0,
    },
    Area: {
        id: 0,
        show_pointer_mark: false,
        isAxis: false,
        axis_txt_size: 0,
        is_axis_txt_italic: false,
        is_axis_txt_bold: false,
        axis_txt_color: "",
        axisX: "",
        axisY: "",
        isLegend: false,
        legend_size: 0,
        is_legend_italic: false,
        is_legend_bold: false,
        legend_color: "",
        thickness: 0,
        is_line_smoth: false,
        projectId: 0,
    },
    Line: {
        id: 0,
        show_pointer_mark: false,
        isAxis: false,
        axis_txt_size: 0,
        is_axis_txt_italic: false,
        is_axis_txt_bold: false,
        axis_txt_color: "",
        axisX: "",
        axisY: "",
        isLegend: false,
        legend_size: 0,
        is_legend_italic: false,
        is_legend_bold: false,
        legend_color: "",
        thickness: 0,
        is_line_smoth: false,
        projectId: 0,
    },
    Column_Area: {
        id: 0,
        b_bar_spacing: 0,
        b_border_radius: 0,
        b_border_bld: 0,
        b_border_color: "",
        b_isLegend: false,
        b_legend_size: 0,
        b_is_legend_italic: false,
        b_is_legend_bold: false,
        b_legend_color: "",
        b_isAxis: false,
        b_axis_txt_size: 0,
        b_is_axis_txt_italic: false,
        b_is_axis_txt_bold: false,
        b_axis_txt_color: "",
        b_axisX: "",
        b_axisY: "",
        a_show_pointer_mark: false,
        a_isAxis: false,
        a_axis_txt_size: 0,
        a_is_axis_txt_italic: false,
        a_is_axis_txt_bold: false,
        a_axis_txt_color: "",
        a_axisX: "",
        a_axisY: "",
        a_isLegend: false,
        a_legend_size: 0,
        a_is_legend_italic: false,
        a_is_legend_bold: false,
        a_legend_color: "",
        a_thickness: 0,
        a_is_line_smoth: false,
        projectId: 0,
    },
    Column_Line: {
        id: 0,
        b_bar_spacing: 0,
        b_border_radius: 0,
        b_border_bld: 0,
        b_border_color: "",
        b_isLegend: false,
        b_legend_size: 0,
        b_is_legend_italic: false,
        b_is_legend_bold: false,
        b_legend_color: "",
        b_isAxis: false,
        b_axis_txt_size: 0,
        b_is_axis_txt_italic: false,
        b_is_axis_txt_bold: false,
        b_axis_txt_color: "",
        b_axisX: "",
        b_axisY: "",
        l_show_pointer_mark: false,
        l_isAxis: false,
        l_axis_txt_size: 0,
        l_is_axis_txt_italic: false,
        l_is_axis_txt_bold: false,
        l_axis_txt_color: "",
        l_axisX: "",
        l_axisY: "",
        l_isLegend: false,
        l_legend_size: 0,
        l_is_legend_italic: false,
        l_is_legend_bold: false,
        l_legend_color: "",
        l_thickness: 0,
        l_is_line_smoth: false,
        projectId: 0,
    },
};

const updateGraphProject = createSlice({
    name: "graphUpdater",
    initialState: initialProject,
    reducers: {
        updateGraphs: (state, action) => {
            if (action.payload) {
                console.log("+++", action.payload, state);
                return (state = action.payload);
            }
        },
    },
});

export const { updateGraphs } = updateGraphProject.actions;

export default updateGraphProject.reducer;
